# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regform', '0003_auto_20171010_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='email',
            field=models.EmailField(blank=True, max_length=200, verbose_name='Email Address: (example: abc@example.com)'),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='full_name',
            field=models.CharField(blank=True, max_length=60, verbose_name='Full name:'),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender:'),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='lga',
            field=models.CharField(blank=True, max_length=100, verbose_name='LGA:'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='business_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Business Address:'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Occupation:'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='skills',
            field=models.CharField(blank=True, max_length=100, verbose_name='Skills/Talents:'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='sports',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sports:'),
        ),
    ]
